# Customize this file, documentation can be found here:
# https://docs.fastlane.tools/actions/
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.64.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    # cocoapods
    # carthage
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    code_sign_identity = options[:code_sign_identity] || 'iPhone Distribution'
    provisioning_profile_specifier = 'AB Inbev Tapwiser QA'
    development_team = options[:development_team] || '2JFB7H5D45'

    automatic_code_signing(
      path: 'Dojo-iOS-Basico.xcodeproj',
      targets: 'Dojo-iOS-Basico'
    )

    gym(
      silent: 'true',
      export_method: 'enterprise',
      scheme: scheme,
      configuration: configuration,
      codesigning_identity: code_sign_identity,
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{provisioning_profile_specifier}' "\
              "DEVELOPMENT_TEAM='#{development_team}'",
      derived_data_path: derived_data_path,
      build_path: build_path,
      buildlog_path: buildlog_path,
      output_directory: output_directory
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used. No personal data is recorded.
# Learn more at https://docs.fastlane.tools/#metrics
